# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

compatible: "zmk,input-processor-caret"

description: Custom input processor for pointer-to-caret (arrow keys).

properties:
  caret-tick:
    type: int
    required: false
    description: Delta threshold for arrow key press 