manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: semtexfromua
      url-base: https://github.com/semtexfromua
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-pmw3610-driver_mod
      remote: semtexfromua
      revision: main
  self:
    path: config
